services:
  postgres:
    image: postgres:16          # ä½¿ç”¨ PG 16
    container_name: nest-pg
    restart: always
    ports:
      - '5432:5432'             # âš ï¸ ç«¯å£æ˜¯ 5432
    environment:
      POSTGRES_USER: root       # è´¦å·
      POSTGRES_PASSWORD: root   # ğŸ” å¯†ç 
      POSTGRES_DB: todo_db      # ğŸ“‚ æ•°æ®åº“å
    volumes:
      - ./pg_data:/var/lib/postgresql/data # æ•°æ®æŒä¹…åŒ–